.job_template: &job_definition
  variables:
    GRADLE_OPTS: "-Xmx386m -Xms386m"
  script:
    - echo PATH = ${PATH}
    - echo JAVA_HOME = ${JAVA_HOME}
    - java -Xmx32m -version
    - ./gradlew build testRecentVersionCompatibility --info

openjdk7:
  <<: *job_definition
  image: openjdk:7-jdk
  before_script: # Workaround for https://github.com/travis-ci/travis-ci/issues/8503
    - sudo sed -i 's/security.provider.9/#security.provider.9/g' $JAVA_HOME/jre/lib/security/java.security
  variables:
    GRADLE_OPTS: "-Xmx386m -Xms386m -XX:MaxPermSize=128m" # Java 7 still uses separate permgen

openjdk8:
  <<: *job_definition
  image: openjdk:8-jdk

openjdk9:
  <<: *job_definition
  image: openjdk:9-jdk

openjdk10:
  <<: *job_definition
  image: openjdk:10-jdk

openjdk11:
  <<: *job_definition
  image: openjdk:11-jdk
