sudo: false
language: java
env:
  global:
    - TERM=dumb
    - GRADLE_OPTS=-Xmx386m -Xms386m
install: true
script: ./gradlew build testVersionCompatibility
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
