sudo: true
dist: trusty
language: java

install: true

matrix:
  include:
# 7
    - env: JDK='Oracle JDK 7'
      jdk: oraclejdk7
    - env: JDK='OpenJDK 7'
      jdk: openjdk7
      before_script: # Try a workaround for https://github.com/travis-ci/travis-ci/issues/8503
      - sudo sed -i 's/security.provider.9/#security.provider.9/g' $JAVA_HOME/jre/lib/security/java.security
# 8
    - env: JDK='Oracle JDK 8'
      jdk: oraclejdk8
    - env: JDK='OpenJDK 8'
      jdk: openjdk8
# 9
    - env: JDK='Oracle JDK 9'
      jdk: oraclejdk9
    - env: JDK='OpenJDK 9'
      jdk: openjdk9
# 10
    - env: JDK='Oracle JDK 10'
      jdk: oraclejdk10
    - env: JDK='OpenJDK 10'
      jdk: openjdk10
# 11
    - env: JDK='Oracle JDK 11'
      jdk: oraclejdk11
    - env: JDK='OpenJDK 11'
      jdk: openjdk11
  allow_failures:
    - env: JDK='Oracle JDK 7'
    - env: JDK='OpenJDK 7'
    - env: JDK='Oracle JDK 11'
    - env: JDK='OpenJDK 11'

env:
  global:
    - GRADLE_OPTS="-Xmx386m -Xms386m"

script:
  - echo PATH = ${PATH}
  - echo JAVA_HOME = ${JAVA_HOME}
  - ls -LRl $JAVA_HOME
  - java -Xmx32m -version
  - ./gradlew build testRecentVersionCompatibility --info
