sudo: false
language: java
env:
  global:
    - TERM=dumb
    - GRADLE_OPTS=-Xmx386m -Xms386m -Dorg.gradle.parallel.intra=true
install: true
script: ./gradlew --parallel --max-workers=2 build testVersionCompatibility
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
