sudo: false
language: java
env:
  global:
    - TERM=dumb
    - GRADLE_OPTS=-Xmx386m -Xms386m
install: true
script: ./gradlew build testRecentVersionCompatibility
matrix:
  include:
    - jdk: oraclejdk8
    - jdk: oraclejdk7
      env:
        - GRADLE_OPTS=-Xmx386m -Xms386m -XX:MaxPermSize=128m
    - jdk: openjdk7
    - jdk: openjdk6
