sudo: true
dist: trusty
language: java

install: true

matrix:
  include:
    - jdk: openjdk7
      env: GRADLE_OPTS="-Xmx386m -Xms386m -XX:MaxPermSize=128m" # Java 7 still uses separate permgen
      before_script: # Workaround for https://github.com/travis-ci/travis-ci/issues/8503
        - sudo sed -i 's/security.provider.9/#security.provider.9/g' $JAVA_HOME/jre/lib/security/java.security
    - jdk: openjdk8
    - jdk: openjdk9
    - jdk: openjdk10
    - jdk: openjdk11

env:
  global:
    - GRADLE_OPTS="-Xmx386m -Xms386m"

script:
  - echo PATH = ${PATH}
  - echo JAVA_HOME = ${JAVA_HOME}
  - java -Xmx32m -version
  - ./gradlew build testRecentVersionCompatibility --info
