sudo: true
dist: trusty
language: java

install: true

matrix:
  include:
    - jdk: openjdk8
    - jdk: openjdk9
    - jdk: openjdk10
    - jdk: openjdk11
    - jdk: openjdk12
    - jdk: openjdk-ea
  allow_failures:
    - jdk: openjdk-ea

env:
  global:
    - GRADLE_OPTS="-Xmx386m -Xms386m"

script:
  - echo PATH = ${PATH}
  - echo JAVA_HOME = ${JAVA_HOME}
  - java -Xmx32m -version
  - ./gradlew build testRecentVersionCompatibility --info
